// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngukwbvyeszhrpytwxvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndWt3YnZ5ZXN6aHJweXR3eHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMzQ4ODksImV4cCI6MjA1MzkxMDg4OX0.fRuNX-jk3j8N0z0a5SUIWRaZ9r2UAN6q4SyB345zphs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);